name: soundcard_server workflow for Codecov on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
